//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plant_Smart.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataLog
    {
        public int Id { get; set; }
        public System.Guid PlantId { get; set; }
        public Nullable<double> Temperature { get; set; }
        public Nullable<double> Humidity { get; set; }
        public Nullable<double> SoilMoisture { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Plant Plant { get; set; }
    }
}
